
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ingestor'
    static_configs:
      - targets: ['ingestor:8081']

  - job_name: 'parser'
    static_configs:
      - targets: ['parser:8080']

  - job_name: 'storage-writer'
    static_configs:
      - targets: ['storage-writer:8080']
