{
 "title": "Log Pipeline Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Failed to store by storage writer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storage_writer_logs_failed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs stored by storage writer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storage_writer_logs_stored_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs failed by Parser",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "parser_logs_failed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs processed Total (Parser)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "parser_logs_processed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Invalid Logs (Ingestor)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ingestor_invalid_logs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Logs recieved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ingestor_logs_received_total", "legendFormat": "__auto" }
   ]
  }
 ]
}